routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.page');
});

Route::get('/dashboard', function () {
    if(Auth::check() && Auth::user()->rol == 'usuario'){
        return view('usuario.index');
    }elseif (Auth::check() && Auth::user()->rol == 'instructor'){
        return view('instructor.index');
    }elseif (Auth::check() && Auth::user()->rol == 'administrador'){
        return view('administrador.index');
    }elseif (Auth::check() && Auth::user()->rol == 'empresa'){
        return redirect()->action('EmpresaController@index');
    }
    else{
        return view('auth.login');
    }

});

Auth::routes();





//vista de Cursos empresa



//vistas de usuario
Route::get('cursos/{nombre}/{id}','CursoController@perfilCursoUsuario');


//ciudad
Route::get('/home/{departamento_id}', ['uses' => 'HomeController@buscar_ciudades', 'as' => 'load.cities']);

//EDITAR DATOS CADA USUARIO
Route::get('miperfil','UsuarioController@index');
Route::post('ActualizarPerfil/{id}','UsuarioController@update');
Route::get('seguridad','UsuarioController@ActualizarPass');
Route::post('actualizarPass','UsuarioController@pass');

//Curso
Route::get('curso','CursoController@index');
Route::get('new_curso','CursoController@newcurso');

//Administrador
//crear instructores
Route::get('instructores','AdministradorController@instructor');
Route::get('empresas','AdministradorController@empresas');
Route::get('usuarios','AdministradorController@usuario');
Route::resource('administrador','AdministradorController');


//Instructor
Route::resource('instructor','InstructorController');

//empresas
Route::resource('empresa','EmpresaController');
//USUARIO
Route::resource('usuario','EstudianteController');
Route::get('miscursos','CursoController@miscursos');

//Categorias
Route::resource('categorias','CategoriaController');
Auth::routes();

Route::get('/home', 'HomeController@index');


//Curso
Route::get('curso','CursoController@index');
Route::get('perfil_curso/{id}','CursoController@perfil');
Route::get('new_curso','CursoController@newcurso');
Route::post('guardar_curso','CursoController@store');
Route::get('curso/{id}/editar','CursoController@edit');
Route::post('editando_curso/{id}','CursoController@update');
Route::get('eliminar_curso/{id}','CursoController@destroy');

//Material de apoyo, se asocia con el curso
Route::get('subirmaterialdeapoyo_curso','CursoController@materialApoyoCrear');
Route::post('guardar_materialApoyo_curso','CursoController@guardarmaterial');
Route::get('material_curso/{id}/editar','CursoController@editarmaterial');
Route::post('editando_material_curso/{id}','CursoController@updatematerial');
Route::get('eliminar_material_curso/{id}','CursoController@destroymaterial');

//Modulo
Route::get('modulo','ModuloController@index');
Route::get('new_modulo','ModuloController@newmodulo');
Route::post('guardar_modulo','ModuloController@store');
Route::get('modulo/{id}/editar','ModuloController@edit');
Route::post('editando_modulo/{id}','ModuloController@update');
Route::get('eliminar_modulo/{id}','ModuloController@destroy');

//Material de apoyo, se asocia con el modulo
Route::get('subirmaterialdeapoyo_modulo','ModuloController@materialApoyoCrear');
Route::post('guardar_materialApoyo_modulo','ModuloController@guardarmaterial');
Route::get('material_modulo/{id}/editar','ModuloController@editarmaterial');
Route::post('editando_material_modulo/{id}','ModuloController@updatematerial');
Route::get('eliminar_material_modulo/{id}','ModuloController@destroymaterial');

//Materias
Route::get('materia','MateriaController@index');
Route::get('new_materia','MateriaController@newmateria');
Route::post('guardar_materia','MateriaController@store');
Route::get('materia/{id}/editar','MateriaController@edit');
Route::post('editando_materia/{id}','MateriaController@update');
Route::get('eliminar_materia/{id}','MateriaController@destroy');

//Material de apoyo, se asocia con la materias
Route::get('subirmaterialdeapoyo','MateriaController@materialApoyoCrear');
Route::post('guardar_materialApoyo','MateriaController@guardarmaterial');
Route::get('material/{id}/editar','MateriaController@editarmaterial');
Route::post('editando_material/{id}','MateriaController@updatematerial');
Route::get('eliminar_material/{id}','MateriaController@destroymaterila');

//Lecciones
Route::get('leccion','LeccionController@index');
Route::get('new_leccion','LeccionController@newleccion');
Route::post('guardar_leccion','LeccionController@store');
Route::get('leccion/{id}/editar','LeccionController@edit');
Route::post('editando_leccion/{id}','LeccionController@update');
Route::get('eliminar_leccion/{id}','LeccionController@destroy');

//Material de apoyo, se asocia con la leccion
Route::get('subirmaterialdeapoyo_leccion','LeccionController@materialApoyoCrear');
Route::post('guardar_materialApoyo_lecciono','LeccionController@guardarmaterial');
Route::get('material_leccion/{id}/editar','LeccionController@editarmaterial');
Route::post('editando_material_leccion/{id}','LeccionController@updatematerial');
Route::get('eliminar_material_leccion/{id}','LeccionController@destroymaterial');


//quiz
Route::get('nuevoquiz','QuizController@create');
Route::get('quiz','QuizController@index');
Route::get('quizEdit/{id}','QuizController@edit');
Route::post('crearQuiz','QuizController@store');


/*
 * Quiz leccion
 */

Route::get('quiz_leccion','QuizController@indexQuizLeccion');
Route::get('quiz_leccion_crear','QuizController@createQuizLeccion');
Route::post('quiz_leccion_guardar','QuizController@storeQuizLeccion');
Route::get('quiz_leccion_editar/{id}','QuizController@editQuizLeccion');
Route::post('quiz_leccion_actualizar/{id}','QuizController@updateQuizLeccion');

//pregunta leccion
Route::post('quiz_preguta_crear/{id}','QuizController@guardarPregunta');
Route::post('quiz_preguta_actualizar_leccion/{id}','QuizController@quizpreguntaleccionactualzar');
//Route::post('quiz_preguta_informaion','QuizController@quiz_preguta_informaion');
Route::get('eliminarPreguntaLeccion/{id}','QuizController@eliminarPreguntaLeccion');






//compra paypal
Route::get('payment', array(
    'as' => 'payment',
    'uses' => 'PaypalController@postPayment',
));

Route::get('payment/status', array(
    'as' => 'payment.status',
    'uses' => 'PaypalController@getPaymentStatus',
));

//CARRITO DE COMPRAS
Route::post('addcarrito','CarritoController@store');
Route::get('carrito','CarritoController@index');
Route::resource('cart','CarritoController');
//Route::get('payment/status','CarritoController@compras');

app/Http/Controllers/AdministradorController.php
<?php

namespace App\Http\Controllers;

use App\Ciudad;
use App\Departamento;
use App\Http\Requests\AdministradorRequest;
use App\User;
use Illuminate\Http\Request;
use Redirect;
use Auth;

class AdministradorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $administradores = User::where('rol','=','administrador')->get();
        $departamento = Departamento::All();
        return view('administrador.administradores',compact('administradores','departamento'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdministradorRequest $request)
    {
        $administrador = new User;
        $administrador->name = $request->name;
        $administrador->apellidos = $request->apellidos;
        $administrador->tipo_documento = $request->tipo_documento;
        $administrador->documento = $request->documento;
        $administrador->direccion = $request->direccion;
        $administrador->telefono = $request->telefono;
        $administrador->email = $request->email;
        $administrador->password = bcrypt($request->password);
        $administrador->rol = 'administrador';
        $administrador->ciudad_id = $request->ciudad;
        $administrador->save();
        return redirect('administrador')->with('message','Administrador Creado correctamnete');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $departamento = Departamento::All();
        $ciudad = Ciudad::All();
        $administrador = User::find($id);
        return view('administrador.edit',compact('administrador','departamento','ciudad'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $administrador = User::find($id);
        //$administador->fill($request->all());
        $administrador->name = $request->name;
        $administrador->apellidos = $request->apellidos;
        $administrador->tipo_documento = $request->tipo_documento;
        $administrador->documento = $request->documento;
        $administrador->direccion = $request->direccion;
        $administrador->telefono = $request->telefono;
        $administrador->email = $request->email;
        if ($request->password == ''){
            $administrador->password = $administrador->password;
        }else{
            $administrador->password = bcrypt($request->password);
        }
        $administrador->save();

        return redirect('administrador/'.$id.'/edit')->with('message','Administrador Actualizado correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        return redirect('administrador')->with('message', 'Administrador Eliminado correctamente');
    }

    public function instructor(){
        $instructores = User::where('rol','=','instructor')->get();
        $departamento = Departamento::All();
        return view('administrador.instructores',compact('instructores','departamento'));
    }
    public function empresas(){
        $empresas = User::where('rol','=','empresa')->get();
        $departamento = Departamento::All();
        return view('administrador.empresas',compact('empresas','departamento'));
    }
    public function usuario(){
        $usuarios = User::where('rol','=','usuario')->get();
        $departamento = Departamento::All();
        return view('administrador.usuarios',compact('usuarios','departamento'));
    }
}

resources/views/administrador/edit.blade.php
@extends('layouts.principal')
@section('content')
    <div class="mdk-drawer-layout__content">
        <div class="container-fluid">
            <div class="container">

                <!--   <ol class="breadcrumb">
                       <li class="breadcrumb-item"><a href="fixed-student-dashboard.html">Home</a></li>
                       <li class="breadcrumb-item active">Edit Account</li>
                   </ol>-->
                @if($message=Session::has('message'))
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                        {{Session::get('message')}}
                    </div>
                @endif
                <div class="row">
                    <div class="col-md-12">

                        <div class="card">
                            <div class="card-block">
                                Editar Administrador
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">

                        <div class="card">
                            <div class="card-block">
                                {!! Form::model($administrador,['route'=>['administrador.update',$administrador->id],'method'=>'PUT']) !!}
                                {{ csrf_field() }}
                                @if(count($errors) > 0)
                                    <div class="alert alert-danger sing-box" role="alert">
                                        <ul>
                                            @foreach($errors->all() as $errors)
                                                <li>{!! $errors !!}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <div class="col-lg-6">
                                    <fieldset class="form-group">
                                        <label for="exampleInputEmail1">Nombres</label>
                                        {!! Form::text('name',null,['class'=>'form-control','placeholder'=>'Nombres']) !!}
                                    </fieldset>
                                    <fieldset class="form-group">
                                        <label for="exampleInputEmail1">Apellidos</label>
                                        {!! Form::text('apellidos',null,['class'=>'form-control','placeholder'=>'Apellidos']) !!}
                                    </fieldset>
                                    <div class="form-group">
                                        <label>Tipo Documento</label>
                                        {!! Form::select('tipo_documento', [
                                          'Cedula ciudadania' => 'Cedula ciudadania',
                                          'Cedula extranjera' => 'Cedula extranjera',
                                          'Nit' => 'Nit',],null,['class' => 'form-control']
                                                              ) !!}
                                    </div>
                                    <fieldset class="form-group">
                                        <label for="exampleInputEmail1">Documento</label>
                                        {!! Form::text('documento',null,['class'=>'form-control','placeholder'=>'Documento']) !!}
                                    </fieldset>
                                    <fieldset class="form-group">
                                        <label for="exampleInputEmail1">Correo Electronico</label>
                                        {!! Form::text('email',null,['class'=>'form-control','placeholder'=>'Correo electronico']) !!}
                                    </fieldset>

                                </div>
                              <div class="col-lg-6">

                                  <fieldset class="form-group">
                                      <label for="exampleInputEmail1">Direccion</label>
                                      {!! Form::text('direccion',null,['class'=>'form-control','placeholder'=>'Direccion']) !!}
                                  </fieldset>
                                  <fieldset class="form-group">
                                      <label for="exampleInputEmail1">Telefono</label>
                                      {!! Form::text('telefono',null,['class'=>'form-control','placeholder'=>'Telefono']) !!}
                                  </fieldset>
                                  <fieldset class="form-group">
                                      <label for="exampleInputEmail1">Contraseña</label>
                                      <input type="password" class="form-control" name="password" placeholder="Contraseña">
                                  </fieldset>
                                  <button type="submit" class="btn btn-primary btn-space">Actualizar Administrador</button>
                              </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/administrador/empresas.blade.php
@extends('layouts.principal')
@section('content')
    <div class="mdk-drawer-layout__content">
        <div class="container-fluid">
            <div class="container">

                <!--   <ol class="breadcrumb">
                       <li class="breadcrumb-item"><a href="fixed-student-dashboard.html">Home</a></li>
                       <li class="breadcrumb-item active">Edit Account</li>
                   </ol>-->
                @if($message=Session::has('message'))
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                        {{Session::get('message')}}
                    </div>
                @endif

                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-block">
                                <h3>Crear Empresa</h3>
                                {!! Form::open(['route'=>'empresa.store','method'=>'POST']) !!}
                                {{ csrf_field() }}
                                @if(count($errors) > 0)
                                    <div class="alert alert-danger sing-box" role="alert">
                                        <ul>
                                            @foreach($errors->all() as $errors)
                                                <li>{!! $errors !!}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group xs-pt-10">
                                            <label>Razon Social</label>
                                            <input type="text" placeholder="Nombre" name="razon_social" class="form-control" value="{{ old('name') }}" >
                                        </div>
                                        <div class="form-group">
                                            <label>Tipo Documento</label>
                                            <select class="form-control" name="tipo_documento">
                                                <option>Nit</option>
                                            </select>
                                        </div>
                                        <div class="form-group xs-pt-10">
                                            <label>Documento</label>
                                            <input type="text" placeholder="Numero documento" name="documento" value="{{ old('documento') }}"  class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label>Departamento</label>
                                            <select class="form-control" name="departamento" id="departamento"
                                                    onchange="LoadCities(this.value)">
                                                <option>Seleccione un departamento</option>
                                                @foreach($departamento as $departamentos)
                                                    <option value="{{$departamentos->id}}">{{$departamentos->nombre}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <script>
                                            function LoadCities(departamento_id) {
                                                //alert(departamento_id);
                                                $.get('home/' + departamento_id, function (respuesta) {
                                                    //console.log(respuesta);
                                                    $("#ciudad").empty();
                                                    $("#ciudad").append(new Option("Seleccione una Ciudad"));
                                                    $.each(respuesta, function (index, value) {
                                                        //console.log(value.nombre);
                                                        $("#ciudad").append(new Option(value.nombre, value.id));
                                                    });
                                                });
                                            }
                                        </script>
                                        <div class="form-group">
                                            <label>Ciudad</label>
                                            <select class="form-control" name="ciudad" id="ciudad">
                                            </select>
                                        </div>

                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group xs-pt-10">
                                            <label>Dirección</label>
                                            <input type="text" placeholder="Dirección" name="direccion" value="{{ old('direccion') }}"  class="form-control">
                                        </div>
                                        <div class="form-group xs-pt-10">
                                            <label>Telefono</label>
                                            <input type="text" placeholder="Telefono" value="{{ old('telefono1') }}"  name="telefono" class="form-control">
                                        </div>
                                        <div class="form-group xs-pt-10">
                                            <label>Correo eléctronico</label>
                                            <input type="text" placeholder="Correo electronico" value="{{ old('email') }}"  name="email" class="form-control">
                                        </div>
                                        <div class="form-group xs-pt-10">
                                            <label>Contraseña</label>
                                            <input type="password" placeholder="Contraseña" name="password" class="form-control">
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-space">Crear Empresa</button>
                                    </div>
                                    <div>
                                        <div></div>
                                    </div>
                                </div>
                                {!! Form::close() !!}



                            </div>
                        </div>

                        <div class="card">
                            <div class="card-block">
                                <div>

                                    <br>
                                    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                        <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Creado</th>
                                            <th>Nombre</th>
                                            <th>Apellidos</th>
                                            <th>Email</th>
                                            <th>Telefono</th>
                                            <th>Acción</th>
                                        </tr>
                                        </thead>
                                        <tfoot>
                                        <tr>
                                            <th>Id</th>
                                            <th>Creado</th>
                                            <th>Nombre</th>
                                            <th>Apellidos</th>
                                            <th>Email</th>
                                            <th>Telefono</th>
                                            <th>Acción</th>
                                        </tr>
                                        </tfoot>
                                        <tbody>
                                        @foreach($empresas as $empresa)
                                            <tr>
                                                <td>{{$empresa->id}}</td>
                                                <td>{{$empresa->created_at}}</td>
                                                <td>{{$empresa->name}}</td>
                                                <td>{{$empresa->apellidos}}</td>
                                                <td>{{$empresa->email}}</td>
                                                <td>{{$empresa->telefono}}</td>
                                                <td>
                                                    {!! link_to_route('empresa.edit', $title = 'Editar', $parameters = $empresa->id, $attributes = ['class'=>'btn btn-primary block']) !!}
                                                    <br><br>
                                                    {!!Form::open(['route'=>['empresa.destroy',$empresa->id],'method'=>'DELETE'])!!}
                                                    {!! Form::submit('Eliminar',['class'=>'btn btn-danger block']) !!}
                                                    {!! Form::close() !!}
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>







            </div>
        </div>
    </div>
@stop

resources/views/administrador/index.blade.php
@extends('layouts.principal')
@section('content')
   <!-- <div class="mdk-drawer-layout__content">-->
        <div class="container-fluid">
            <div class="container">

                <!--   <ol class="breadcrumb">
                       <li class="breadcrumb-item"><a href="fixed-student-dashboard.html">Home</a></li>
                       <li class="breadcrumb-item active">Edit Account</li>
                   </ol>-->
                @if($message=Session::has('message'))
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                        {{Session::get('message')}}
                    </div>
                @endif
                <div class="row">
                    <div class="col-md-12">

                        <div class="card">
                            <div class="card-block">
                              <h3>Bienvenido, {{Auth::user()->name}} {{Auth::user()->apellidos}}</h3>
                               <span style="text-transform: uppercase;">{{Auth::user()->rol}}</span>
                            </div>
                        </div>


                    </div>
                </div>







            </div>
        </div>
    <!--</div>-->
@stop